server:
  port: 8081
  shutdown: graceful

spring:

  #Database Conf
  datasource:
    url: jdbc:postgresql://localhost:15432/odontoapp?currentSchema=public
    username: "odontoapp"
    password: "odontoapp"
    driver-class-name: "org.postgresql.Driver"

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    locations: "db/migration"
    baseline-on-migrate: false

springdoc:
  swagger-ui:
    path: "/schedule/swagger-ui.html"

holiday-api:
  url: "https://api.invertexto.com/v1/holidays/"
  token: "${holiday-api-token}"