CREATE TABLE if not exists service (
  service_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(50),
   duration INTEGER NOT NULL,
   CONSTRAINT pk_service PRIMARY KEY (service_id)
);